src/openalpr/support/filesystem.cpp

openalpr currently fails compilation on OS X/Darwin because it doesn't support `stat_buf.st_ctim` functions.

Use Darwin stat functions when applicable.

---

bindings/csharp/openalpr-net/openalpr-net.cpp

Hello Matt, it's Dimitar Dobrev. I am sending you a patch for the crash I had with the .NET binding. I am actually puzzled about why it works for you. Anyway, let me know of there are problems with the patch.

Exposed the third param for a run-time dir to the C# binding thus preventing crashes

---

src/misc_utilities/prepcharsfortraining.cpp

adding space between characters will avoid box overlapping and greatly reduce the failures in the training process (it helps find good blobs).

added space between characters for better training

---

src/openalpr/detection/detectormorph.cpp

I was testing morph detector and found out it had the same issue as the gpu detector, it needs this check before converting to grayscale to avoid the assertion.

fixes assertion in morph detector

---

src/misc_utilities/classifychars.cpp
src/openalpr/support/utf8.cpp

Fixing compiler errors:
error: implicit instantiation of undefined template
error: use of undeclared identifier 'SPACE'

Fixing compiler error for MAC OS 10.10.3

---

src/bindings/python/openalpr.py

Hi Matt,
This is the fix I mentioned on the forum, I got around to doing a proper pull request. All calls to free_json_mem_func have their argument wrapped like this:
```python
self._free_json_mem_func(ctypes.c_void_p(ptr))
```
to avoid the malloc "pointer being freed was not allocated" error when ptr got truncated on the Python side.
Cheers,
Robin

Cast ptr to void_p when passing back to freeJsonMem()

---

config/openalpr.conf.in
src/openalpr/alpr_impl.cpp
src/openalpr/config.cpp
src/openalpr/postprocess/postprocess.cpp
src/openalpr/postprocess/postprocess.h

Attempt #2 - this time with significant refactoring
**Original issues**
* There was a bug in the pruning that could lead to incorrect results for permutations 3 and higher.  The permutations were not being traversed in scoring order while being removed (topN check)
* The check for min/max characters was happening too late and could cause the number of results to be less than topN.
**Changes**
* The refactored code combines the pruning, possibility generation, sorting and template matching into a single pass:
* findAllPermutations - loops through each permutation in scoring order using a priority queue.  For each permutation, it calls analyzePermutation.  The loops stops once topN possibilities have been identified.
* analyzePermutation - generates the possibility, checks for min/max …

TopN values strange behavior #135

---

config/alprd.conf
src/video/videobuffer.cpp

Just add stream=webcam to alprd.conf
Implementation uses the same mechanism used in "alpr": 
cv::VideoCapture cap=cv::VideoCapture();
cap.open(0);

Add support for local webcam in alprd

---

config/openalpr.conf.in
src/openalpr/alpr_impl.cpp
src/openalpr/config.cpp
src/openalpr/config.h

Generating the results for the character details in alpr_impl.cpp can add significant time to the overall plate analysis.  When returning 10 plates, that code took 16% of the total time.  The data returned seems to only be valuable to certain clients of the library (not the default main.cpp client).
I added timing output and a configuration flag to disable the logic.
Since I don't know the context of the functionality, there might be a better way of handling this, like passing the flag directly as input to the analyze() method or by outputing the character details only during debugging.

Added configuration option to disable output of character details in results

---

src/openalpr/alpr_impl.cpp

When searching for best plate index if there are two results that matches the country template and if one of them is at index 0 than the second matching result will be selected as best result.

Fixed best plate selection

---

src/CMakeLists.txt
src/statedetection/CMakeLists.txt

Hi there,
I am not sure if this is the best approach for what I am trying to do, so feedback is welcome.  
For working with the 2.2.x version of alpr and later (which uses opencv 3), I have refactored the `openalpr-ios` project to use a script that will create a universal static iOS openalpr.framework bundle, and will include tesseract, leptonica, and opencv (3) frameworks (as opposed to the current process, which is partially manual).  The script will build openalpr with the aid of a [iOS toolchain file](https://github.com/twelve17/openalpr-ios/blob/2_0/etc/cmake/Toolchains/iOS.cmake), which, among other things, will set the `IOS` CMake variable to `TRUE`.
Along with the above, I am proposing these changes to a couple of the openalpr CMakeLists.txt files to help the two parts work …

Patch for compatibility with openalpr-ios 2_0

---

src/CMakeLists.txt
src/cmake_modules/FindTesseract.cmake
src/cmake_modules/Findlog4cplus.cmake

I have built opemalpr on Mac using macports instead of break. Changes to the build process are as follows:
1. For Tesseract detection I've added /opt/local/ paths to search for includes and libraries
2. I have implemented log4cplus detection similarly to Tesseract via cmake module. Other platforms could also benefit from that.

macports support

---

README.md
doc/man/alpr.1
src/main.cpp

Fix spelling specied -> specified in the description of the --seek command.
I updated the text in the actual --help output, and the README and manpage.

Fix spelling in --seek option documentation.

---

src/openalpr/cjson.c

Daemon was crashing when parsing decimal number from string. It didn't check if current processing char is comma while next character is number.
For example if it was parsing 123,4567 it would convert just 123 to number, and the ",456" would stay in num array what causes crashing.

fixed daemon crashing

---

src/openalpr/textdetection/characteranalysis.cpp

This function may not work without set goodIndices[i] = false first, or the goodIndices vector would be just the same as the orignalindices...

Update Characteranalysis::filterByOuterMask( )

---

src/openalpr/edges/platecorners.cpp

Though I'm not understand why codes about the SCORING_LINE_CONFIDENCE_WEIGHT in 270th line have been disable,  nor the bad results I get when I tryed to enable this line, I know codes shoulld be clean. (^ - ^ ) Y

remove the variables unused

---

src/openalpr/ocr.cpp

Small fix to check that results from ChoiceIterator are not the same as ResultsIterator before addLetter.

Fixing issue #261

---

src/main.cpp

Fix for alprd to allow input as /dev/video* where * is a number that correlate to the webcam on the system.
Tested on OSX and Debian system (Ubuntu and RPI).

Fix for direct webcam input

---

src/misc_utilities/classifychars.cpp

This fix resolves the compile issue in MacOS due to the undefined constants.

Fixing the build issue in OSX

---

src/main.cpp

`alpr` can now receive an image from standard input (the binary content) like one of these (Note the ending `-` which tells `alpr` to read a binary content from the standard input):
```bash
$ wget -O- -q http://plates.openalpr.com/h786poj.jpg | alpr -
$ cat h786poj.jpg | alpr -
```

Added read from piped standard input support

---

src/openalpr/cjson.c
src/openalpr/config_helper.cpp

In certain locales decimal separator is comma instead of a dot.
Without this change OpenALPR will silently fail or produce
meaningless error from underlying OpenCV function.
Additionally json produced will not be valid.

Set locale to avoid numeric conversion issues

---

src/bindings/java/com_openalpr_jni_Alpr.h
src/bindings/java/openalprjni.cpp
src/bindings/java/src/com/openalpr/jni/Alpr.java

When working with JVM based language and OpenCV you may have a ptr to
the native Mat data. This binding allows passing it to the OpenALPR.
Usage:
Mat mat = ...
alpr.recognize(mat.dataAddr(), mat.channels(), mat.width(), mat.height())

Enhance interop with Java

---

src/CMakeLists.txt
src/bindings/python/openalpr/openalpr.py
src/bindings/python/openalprpy.cpp

I noticed that Java bindings has this - recognizing plates from in-memory images.
I added this to the ctypes-base Python bindings for the same functionality.
I also provided a test script which loads the arguments (also multiple) using OpenCV's cv2 module and recognizes them from numpy arrays; it is also possible to display the results with bounding rectangles.

implemented recognize_ndarray in Python bindings (for cv2 images)

---

src/cmake_modules/FindTesseract.cmake

This is the name for the prepackaged Debian/Ubuntu library.

Add libtesseract as a library name

---

src/openalpr/ocr/tesseract_ocr.cpp

Fixes a bug which would cause Alpr to crash if tesseract didn't return the expected data

tesseract crash fix
