openalpr/openalpr

bindings/csharp/openalpr-net/openalpr-net.cpp
bindings/csharp/openalprnet-windemo/Form1.cs

* removed regions-of-interest workaround code (fixed in [30ee061](https://github.com/openalpr/openalpr/commit/30ee061e2189f4ad982aa95def23861cd8c780ab)
* updated winforms demo

openalpr-net fixes

---

src/openalpr/alpr_impl.cpp

I did a little profiling and saw that a bit of the delay in instantiating Alpr comes from instantiating `StateIdentifier` (specifically, when it instantiates `new BRISK(10, 1, 0.9);`).  
Anyway, this is a stab at an approach to lazy load the `StateIdentifier` when calling either `setDefaultRegion` or  `setDetectRegion` with non-empty values.
I'm not super sure this is the best approach.  What do you think?
(On a side note, my apologies--I noticed that there is a lot of noise in the diff due to white-space cleanup, which I have a macro for.  Let me know if you want me to re-do the diff without changing the white space.)

Lazy load StateIdentifier

---

src/openalpr/detection/detectormorph.cpp

Add new enhancements

---

src/bindings/csharp/openalpr-net/openalpr-net.cpp

Hello Matt,
This is not a complete pull request but rather the basis for a discussion. I have implemented my idea that we discussed a few days ago. I have added a C# method for processing video which raises an event for each frame. I have two requests to you:
1. Can you take a look and tell me if you find it general enough and otherwise appropriate to be included?
2. I haven't tested the event because it's never raised when OpenCV lacks support for FFMPEG. I don't have the time to build OpenCV on my own, and the binaries from your release are not enough - CMake requires the entire structure of an OpenCV set-up. So could you please upload somewhere your OpenCV installation? Of course, if you find the time to test it yourself and decide to merge it, that won't be necessary and I'd only need …

Added an overload to the C# binding for reading plates from a video.

---

src/openalpr/detection/detectormorph.cpp

The routine was incorrectly returning too many garbage rects.

Eliminate false positives

---

src/misc_utilities/classifychars.cpp
src/openalpr/pipeline_data.cpp
src/openalpr/pipeline_data.h

See: https://github.com/openalpr/openalpr/issues/103

Minor bugfixes for classifychars

---

src/openalpr/detection/detectorcuda.cpp

added same check as in cpu detector before converting frame to grayscale, this fixes an assertion error.

fixed assertion in gpu detector

---

src/openalpr/textdetection/platemask.cpp

It seems like error. Are you forget 'else' statement?

Fix: Variable PlateMask::hasPlateMask always false

---

src/openalpr/detection/detectorocl.cpp

Provides the user with information on the available OpenCl devices and on how to select the device to be used.

Provide OpenCL information and instructions.

---

.gitignore
src/bindings/python/openalpr/__init__.py
src/bindings/python/openalpr/openalpr.py

Hi!
I'd like to submit this pull request in support of Issue #223 -- this adds in Python 3 support, as well as some destructors and support for "with" syntax.
Let me know if I need to make any additional changes.
Thanks!

Now with support for Python 3+ (Addresses Issue #223)

---

src/bindings/go/main.go
src/bindings/go/make.sh
src/bindings/go/openalpr/openalpr.go
src/bindings/go/openalprgo.cpp
src/bindings/go/openalprgo.h

Roughly a wrapper for golang, please feel free to leave any feedback. Thanks!
BTW, I only test it on my mac.

initial a wrapper for golang

---

src/openalpr/support/timing.cpp

Hi Matt,
Happy New Year !
Kees

Corrections to Windows timing

---

src/openalpr/licenseplatecandidate.cpp

closes #247 , #216 
* checks for number of channels before performing conversion from BGR to GRAY

Fix grayscale images recognition

---

src/misc_utilities/classifychars.cpp

In classifychars.cpp, application is unable to receive any keys due to waitkey's value not being converted to char in some if conditions. Tested on ubuntu 14.04.

fix waitkey comparisons

---

src/openalpr/edges/platelines.cpp

remove unused local variable

---

src/openalpr/segmentation/charactersegmenter.cpp

I don't think the variable "isOn"  has a special change at this line.

comment out some code look like unused.

---

src/openalpr/segmentation/charactersegmenter.cpp

After the modification, I think the loop will break if pxLeniency is large enough.

Reduce the times for this loop

---

config/alprd.conf.defaults
src/daemon.cpp
src/daemon/daemonconfig.cpp
src/daemon/daemonconfig.h

simple patch to add pattern support to alprd

added alprd.conf option for pattern

---

README.md

We created an iOS binding for React Native (Android soon to come). Happy to share it with others.

Add React Native link to docs

---

src/openalpr/detection/detectorcuda.cpp
src/openalpr/detection/detectorcuda.h

Added some #if checks for opencv major version 2

Fix missing gpu.hpp when compiling with opencv 3.x and -D COMPILE_GPU=1

---

src/openalpr/detection/detectorcuda.cpp

This resolves a potential segfault encounted at line 76 where cuda_cascade is an invalid value.

Fixing potential segfault referencing cuda_cascade

---

src/misc_utilities/calibrate.cpp

Set sliders to correct position when prewarp config provided

openalpr-utils-calibrate set sliders to correct position

---

Dockerfile

This fixes recognition of plates in EXIF-oriented images. See here for
details: https://github.com/openalpr/cloudapi/issues/16#issuecomment-396740100

Use Ubuntu 18.04 in Dockerfile

---

runtime_data/postprocess/br.patterns

See https://pt.wikipedia.org/wiki/Placas_de_identifica%C3%A7%C3%A3o_de_ve%C3%ADculos_no_Brasil#Sequ.C3.AAncias_alfanum.C3.A9ricas

Added all Brazil patterns

---

runtime_data/postprocess/br.patterns

Revert "Revert "Added all Brazil patterns""

---

doc/man/alpr.1
src/CMakeLists.txt
src/main.cpp
src/misc_utilities/binarizefontsheet.cpp
src/misc_utilities/calibrate.cpp
src/misc_utilities/classifychars.cpp
src/misc_utilities/prepcharsfortraining.cpp
src/misc_utilities/tagplates.cpp
src/openalpr/alpr_impl.cpp
src/openalpr/colorfilter.cpp
src/openalpr/detection/detector.cpp
src/openalpr/detection/detectorcpu.cpp
src/openalpr/detection/detectormask.cpp
src/openalpr/detection/detectormorph.cpp
src/openalpr/edges/edgefinder.cpp
src/openalpr/edges/platecorners.cpp
src/openalpr/edges/platelines.cpp
src/openalpr/licenseplatecandidate.cpp
src/openalpr/motiondetector.cpp
src/openalpr/ocr/segmentation/charactersegmenter.cpp
src/openalpr/pipeline_data.cpp
src/openalpr/textdetection/characteranalysis.cpp
src/openalpr/textdetection/linefinder.cpp
src/openalpr/textdetection/platemask.cpp
src/openalpr/textdetection/textcontours.cpp
src/openalpr/textdetection/textline.cpp
src/openalpr/utility.cpp

openCV used to prefix a lot of constants with "CV_". This has been removed with the addition of the cv namespace. I changed all the constants over so it works with openCV version 4. I've compiled and run it successfully on MacOS Catalina.

Updated code to use openCV v4 and gave the right flags to Clang
